version: "3.7"

services:
  material1_db:
    image: postgres
    ports:
      - "${MATERIAL1_DB_PORT:-5432}:5432"
    volumes:
      - material1_db_volume:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    env_file:
      - prod.env
  material1:
    build:
      context: .
      args:
        MATERIAL1_PORT: ${MATERIAL1_PORT:-8080}
    depends_on:
      - material1_db
    env_file:
      - prod.env
    environment:
      MATERIAL1_PORT: ${MATERIAL1_PORT:-8080}
      MATERIAL1_DB_HOST: ${MATERIAL1_DB_HOST:-material1_db}
      MATERIAL1_DB_PORT: ${MATERIAL1_DB_PORT:-5432}

volumes:
  material1_db_volume:
