version: "3.7"

services:
  material1_db:
    env_file: dev.env
  material1_minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - material1_minio_volume:/data
    command: server /data
    env_file: dev.env

volumes:
  material1_minio_volume:
