version: "3.7"

services:
  minio_dev:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ACCESS_KEY: dev_minio_access_key
      MINIO_SECRET_KEY: dev_minio_secret_key
    command: server /data
