version: "3.7"

services:
  material1_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - material1_db_volume:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  material1_db_volume:
