[[section-system-scope-and-context]]
== Kontextabgrenzung

****
[cols="1,1,1" options="header"]
|===
|Kommunikationsbeziehung |Eingabe | Ausgabe
| Weiterleitung von der Gruppenbildung | _Das Gruppenbildungsmodul stellt eine Anfrage mit der GruppenID um einen Weiterleitungslink zu erhalten._ | _Wir liefern einen auf die GruppenID bezogenen Link zurück._
| Überprüfen des Adminstatus eines Nutzer in einer Gruppe | _Wir erfragen mit einer GruppenID und dem Benutzernamen die Berechtigungen eines Nutzers in einer bestimmten Gruppe._  | _Wir erhalten als Bestätigung einen Boolean zurück._
| Abfrage aller Gruppenupdates | _Wir erfragen die Veränderungen in den Gruppendaten seit der letzten Anfrage._ | _Wir erhalten eine Liste aller veränderten Gruppen zurück._
| Erfragen der Mitglieder einer Gruppe | _Wir erfragen mittels einer GruppenID die Mitgliederdaten dieser spezifischen Gruppe._ | Wir erhalten eine Liste von Nutzerdaten zurück._
|===
****

include::../api/external-api.adoc[]

****
Gruppenbildungsservice::

Der Service, der unsere Gruppenverwaltung abwickelt, muss mit der Gruppenbildung interagieren.
Dazu haben wir folgende Anfragen an die REST-API der Gruppenbildung implementiert:

. `doesGroupExist`: fragt ab, ob eine gegebene Gruppe existiert
. `isUserInGroup`: fragt ab, ob ein gegebener User in einer gegebenen Gruppe Mitglied ist
. `isUserAdminInGroup`: fragt ab, ob ein gegebener User in einer gegebenen Gruppe Administrator ist
. `returnAllGroups`: gibt alle Gruppen zurück, die seit einem bestimmten Zeitpunkt, der durch den Parameter `eventId` bestimmt wird, verändert worden sind
. `returnUsersOfGroup`: gibt alle Mitglieder einer Gruppe zurück
. `returnGroupsOfUsers`: gibt alle Gruppen eines Users zurück

Dabei werden von uns nicht alle dieser Anfragen genutzt. Dennoch sind sie implementiert um in Zukunft die Erweiterbarkeit zu vereinfachen.
Diese verschiedenen Anfragen sind notwendig für die verschiedenen Funktionalitäten, die unsere Anwendung bereitstellt:

- Anzeige aller Gruppen
- Garbage Collection (Überprüfen ob eine Gruppe noch existiert)
- Überprüfung von Berechtigungen eines Users
- Erstellung einer Platzhalterberechtigung für alle Rollen

Da uns während der Entwicklungszeit der externe Service nicht zur Verfügung stand, haben wir einen Stub entwickelt,
welcher festgesetzte Rollen zurückgibt. Wir haben uns dazu an dem REST-API Wiki der `Gruppenbildung` orientiert.
****

****
Prometheus

Im `PrometheusComponent` werden unsere Prometheus Statistiken registriert.

Zur Verfügung gestellt werden:

Global:

- Speicherplatzverbrauch
- Dateianzahl
- Ordneranzahl
- Gruppenanzahl

Für jede Gruppe einzeln (mit der Gruppen-UUID der Gruppenbildung getaggt):

- Speicherplatzverbrauch
- Dateianzahl
- Ordneranzahl

****
