[[section-system-scope-and-context]]
== Kontextabgrenzung

****
_Die (technische) Abgrenzung gegenüber allen Kommunikationsbeziehungen (Nachbarsysteme und Benutzerrollen).
Somit werden die externen Schnittstellen festgelegt._

_Festlegung *aller* Kommunikationsbeziehungen mit Erklärung der *fachlichen* Ein- und Ausgabedaten._

_Kontextdiagramme, Listen von Kommunikationsbeziehungen aber auch plain text wären denkbar._
****

[cols="1,1,1" options="header"]
|===
|Kommunikationsbeziehung |Eingabe | Ausgabe
| Requests vom Gruppensystem | _Wir erhalten Requests für die Ordner-/Dateierstellung oder Löschung und den Erhalt von
Dateien aus unserer Datenbank._ | _Wir liefern eine Bestätigung des betreffenden Requests (eventuell inklusive der
gewollten Datei) zurück, wenn die entsprechenden Berechtigungen vorhanden waren. Ansonsten bearbeiten wir den Request
nicht._
| Erfragen von Berechtigungen | _Wir erfragen mit einer Gruppen ID und dem Benutzernamen die Berechtigungen eines
Nutzers in einer bestimmten Gruppe._  | _Wir erhalten ein Datenobjekt (.json) zurück, dass alle Berechtigungen (Rollen) des betreffenden Nutzers beinhaltet._
|===

include::../api/external-api.adoc[]

****
GroupService

Der Service, der unsere Gruppenverwaltung abwickelt, muss mit der GruppenFindung interagieren.
Dazu haben wir folgende REST API Anfragen implementiert:

. `getAllGroups`: gibt alle existierenden Gruppen zurück
. `getAllGroupsOfUser`: gibt alle Gruppen zurück, in der ein gegebener User Mitglied ist
. `fetchRolesInGroup`: gibt alle Rollen in einer gegebenen Gruppe zurück
. `fetchRoleForUserInGroup`: gibt die Rolle eines bestimmten Users in einer gegebenen Gruppe zurück

Diese verschiedenen Anfragen sind notwendig für die verschiedenen Funktionalitäten, die unsere Anwendung bereitstellt:

- Anzeige aller Gruppen
- Garbage Collection (Überprüfen ob eine Gruppe noch existiert)
- Überprüfung von Berechtigungen eines Users
- Erstellung einer Platzhalterberechtigung für alle Rollen

Da uns während der Entwicklungszeit der externe Service nicht zur Verfügung stand, haben wir einen Stub entwickelt, welcher fixe Rollen zurückgibt.
Wir haben uns dazu an dem REST-API Wiki der `Gruppenfindung` orientiert.
****
