[[section-system-scope-and-context]]
== Kontextabgrenzung

****
_Die (technische) Abgrenzung gegenüber allen Kommunikationsbeziehungen (Nachbarsysteme und Benutzerrollen).
Somit werden die externen Schnittstellen festgelegt._

_Festlegung *aller* Kommunikationsbeziehungen mit Erklärung der *fachlichen* Ein- und Ausgabedaten._

_Kontextdiagramme, Listen von Kommunikationsbeziehungen aber auch plain text wären denkbar._
****

[cols="1,1,1" options="header"]
|===
|Kommunikationsbeziehung |Eingabe | Ausgabe
| Requests vom Gruppensystem | _Wir erhalten Requests für die Ordner-/Dateierstellung oder Löschung und den Erhalt von
Dateien aus unserer Datenbank._ | _Wir liefern eine Bestätigung des betreffenden Requests (eventuell inklusive der
gewollten Datei) zurück, wenn die entsprechenden Berechtigungen vorhanden waren. Ansonsten bearbeiten wir den Request
nicht._
| Erfragen von Berechtigungen | _Wir erfragen mit einer Gruppen ID und dem Benutzernamen die Berechtigungen eines
Nutzers in einer bestimmten Gruppe._  | _Wir erhalten ein Datenobjekt (.json) zurück, dass alle Berechtigungen (Rollen) des betreffenden Nutzers beinhaltet._
|===

include::../api/external-api.adoc[]

****
GruppenfindungsService

Der Service, der unsere Gruppenverwaltung abwickelt, muss mit der GruppenFindung interagieren.
Dazu haben wir folgende Anfragen an die REST-API der Gruppenfindung implementiert:

. `doesGroupExist`: fragt ab, ob eine gegebene Gruppe existiert
. `isUserInGroup`: fragt ab, ob ein gegebener User in einer gegebenen Gruppe Mitglied ist
. `isUserAdminInGroup`: fragt ab, ob ein gegebener User in einer gegebenen Gruppe Administrator ist
. `returnAllGroups`: gibt alle Gruppen zurück, die seit einem bestimmten Zeitpunkt, der durch den Parameter `eventId` bestimmt wird, verändert worden sind
. `returnUsersOfGroup`: gibt alle Mitglieder einer Gruppe zurück
. `returnGroupsOfUsers`: gibt alle Gruppen eines Users zurück

Diese verschiedenen Anfragen sind notwendig für die verschiedenen Funktionalitäten, die unsere Anwendung bereitstellt:

- Anzeige aller Gruppen
- Garbage Collection (Überprüfen ob eine Gruppe noch existiert)
- Überprüfung von Berechtigungen eines Users
- Erstellung einer Platzhalterberechtigung für alle Rollen

Da uns während der Entwicklungszeit der externe Service nicht zur Verfügung stand, haben wir einen Stub entwickelt,
welcher festgesetzte Rollen zurückgibt. Wir haben uns dazu an dem REST-API Wiki der `Gruppenfindung` orientiert.
****

****
Prometheus

Im `PrometheusComponent` werden unsere Prometheus Statistiken registriert.

Zur Verfügung gestellt werden:

Global:

- Speicherplatzverbrauch
- Dateianzahl
- Ordneranzahl
- Gruppenanzahl

Für jede Gruppe einzeln (mit der Gruppen-UUID der Gruppenbildung getaggt):

- Speicherplatzverbrauch
- Dateianzahl
- Ordneranzahl

****
