[[section-solution-strategy]]
== Lösungsstrategie

****
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems
prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs-
oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie

Eine *kurze* und *präzise* Darlegung aller relevanten Entscheidungen.
****

== Controller Tests

Eine Schwierigkeit für die Controller Tests ist, dass man die sicherheitsrelevanten Aspekte von `spring-security` und
`keycloak` berücksichtigen muss.
Wir hatten uns zunächst dafür entschieden diesen Teil zu mocken.
Jedoch hatte es bei uns nicht funktioniert den Mock mit `@WithMockUser` zu machen, daher hatten wir den ganzen
SecurityContext gemockt und stellten diesen mit `SecurityContextUtil` für jeden ControllerTest zur Verfügung.
Später wurden wir dann auf die Bibliothek `spring-security-test-keycloack-addons` aufmerksam gemacht, die das Testen
massiv vereinfacht. Nun kann man die Annotation `@WithMockKeycloakAuth` benutzen um Tests mit einer gültigen Keycloak
Authentifizierung auszustatten.

== Datenbank

Zur Auswahl standen hier MySQL, MariaDB und PostgreSQL, da wir damit bereits Erfahrungen gesammelt haben.
Wir haben uns nach einer kurzen Diskussion für MariaDB entschieden.
Und zwar weil MariaDB die aktive Open-Source-Weiterentwicklung von MySQL ist, womit wir am meisten Erfahrung haben.

Leider dauert das Starten der MariaDB-Datenbank in einem Docker-Container recht lange (ähnlich wie MySQL) und es ist
umständlich immer diesen Docker-Container laufen zu lassen. Also haben wir uns entschieden in der Entwicklung und zum
Testen H2 zu benutzen. Das ist eine Embedded In-Memory Datenbank, die sehr schnell startet und die wir bereits kennen
gelernt haben.
