[[section-solution-strategy]]
== Lösungsstrategie

****
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems
prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs-
oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie

Eine *kurze* und *präzise* Darlegung aller relevanten Entscheidungen.
****

=== Controller Tests

****
Eine Schwierigkeit der Controller-Tests liegt in der Berücksichtigung der sicherheitsrelevanten Aspekte von
`spring-security` und `keycloak`.
Wir hatten uns zunächst dafür entschieden diesen Teil zu mocken.
Anfangs hatten wir Probleme, `@WithMockUser` zu verwenden, daher entschieden wir uns für das Mocken des gesamten
SecurityContext. Durch  `SecurityContextUtil` wird dieser jedem ControllerTest zur Verfügung gestellt.
Später wurden wir dann auf die Bibliothek `spring-security-test-keycloack-addons` aufmerksam, die das Testen
massiv vereinfacht. Nun kann man die Annotation `@WithMockKeycloakAuth` benutzen, um Tests mit einer gültigen Keycloak
Authentifizierung auszustatten.
****

=== Datenbank

****

Der Großteil unserer Erfahrungen beruhte bisher auf MySQL. Da MariaDB die aktive Open-Source-Weiterentwicklung von MySQL
ist, haben wir uns zunächst für die Verwendung von MariaDB entschieden.

Leider dauert das Starten der MariaDB-Datenbank in einem Docker-Container recht lange (ähnlich wie MySQL) und es ist
umständlich, diesen Docker-Container dauerhaft aktiviert zu haben. Aus diesem Grund haben wir uns entschieden , während
der Entwicklung und Testing H2 zu verwenden. H2 ist eine Embedded In-Memory Datenbank, die sehr schnell startet und
die wir bereits kennengelernt haben.
****
