[[section-solution-strategy]]
== Lösungsstrategie

****
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems
prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs-
oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie

Eine *kurze* und *präzise* Darlegung aller relevanten Entscheidungen.
****

=== Docker-Compose

****
Beim Design der docker-compose Konfigurationen hatten wir komplizierte Anforderungen.

Ziel:

In Production soll ein `docker-compose [...] up` die Anwendung und alle Dependencies (also nur die Datenbank) starten.

In Development soll ein anderes `docker-compose [...] up` nur die Dependencies (die Datenbank und MinIO) starten, damit
die Anwendung separat aus der IDE gestartet werden kann.

Zusätzlich soll es eine Möglichkeit geben, die Anwendung für Tutoren zu demonstrieren. Noch ein anderer
`docker-compose [...] up` Befehl soll alle Dependencies (diesmal die Datenbank und MinIO) und die Anwendung lokal
starten.

In all diesen Fällen sollen sämtliche Umgebungsvariablen und Startparameter richtig konfiguriert sein.

Gelöst wird dies durch das Benutzen von mehreren `docker-compose` .yml Dateien, die zusammen geladen werden.
Denn `docker-compose` erlaubt es, bereits definierte Services in einer anderen Konfigurationsdatei zu ergänzen.

Also gibt es nun:

`docker-compose.yml`: Enthält die Definition des Datenbank-Containers ohne Konfiguration.

`docker-compose.dev.yml`: Enthält die Definition des MinIO-Containers mit Konfiguration und zusätzlich die Konfiguration
für den in der `docker-compose.yml` definierten Datenbank-Container.

`docker-compose.prod.yml`: Enthält die Definition des Anwendungs-Containers mit Build-Anweisungen und Konfiguration und
zusätzlich die Konfiguration für den in der `docker-compose.yml` definierten Datenbank-Container.

`docker-compose.demo.yml`: Überschreibt Teile der Konfiguration des Anwendungs-Containers aus der
`docker-compose.prod.yml` und fügt ein weiteres `depends_on` auf den MinIO-Container aus `docker-compose.dev.yml` ein.

Geladen werden die Konfigurationen aus den Dateien `dev.env` und `prod.env`.

Somit kann man sich für jeden Fall aus den `docker-compose`-Konfigurationsdateien die passende Konfiguration
zusammenbauen.
****

=== Controller Tests

****
Eine Schwierigkeit der Controller-Tests liegt in der Berücksichtigung der sicherheitsrelevanten Aspekte von
`spring-security` und `keycloak`.
Wir hatten uns zunächst dafür entschieden diesen Teil zu mocken.
Anfangs hatten wir Probleme, `@WithMockUser` zu verwenden, daher entschieden wir uns für das Mocken des gesamten
SecurityContext. Durch  `SecurityContextUtil` wird dieser jedem ControllerTest zur Verfügung gestellt.
Später wurden wir dann auf die Bibliothek `spring-security-test-keycloack-addons` aufmerksam, die das Testen
massiv vereinfacht. Nun kann man die Annotation `@WithMockKeycloakAuth` benutzen, um Tests mit einer gültigen Keycloak
Authentifizierung auszustatten.
****

=== Datenbank

****
Zur Auswahl standen hier MySQL, MariaDB und PostgreSQL, da wir mit diesen Datenbanken bereits Erfahrungen gesammelt
haben.

Der Großteil unserer Erfahrungen beruhte bisher auf MySQL, also haben wir uns zunächst für die neuere Variante MariaDB
entschieden.

Leider dauert das Starten der MariaDB-Datenbank in einem Docker-Container recht lange (ähnlich wie MySQL) und es ist
umständlich, diesen Docker-Container dauerhaft aktiviert zu haben. Aus diesem Grund haben wir uns entschieden, während
des Testings H2 zu verwenden. H2 ist eine Embedded In-Memory Datenbank, die sehr schnell startet und
die wir bereits kennengelernt haben.

Nach einiger Zeit sind wir dann doch auf PostgreSQL umgestiegen, weil es von den Server-Admins der HHU bevorzugt wird
und für ein Testdeployment auf Heroku notwendig ist.
Das war ein schmerzloser Prozess, da wir bis dahin noch nichts mit der echten Datenbank gemacht haben.
****

=== Logging

****
Für das Logging haben wir uns zunächst auf zwei Fälle beschränkt.
Zum einen `info` und `error`.
Die `info` werden ausschließlich in den Controller geschrieben, da es sonst zu redundanten Lognachrichten kommen würde.
Dies ist ausreichend, da jede Aktion unserer Applikation von einem Controller gestartet wird.

Die `error`-Nachrichten werden an jeder Stelle geschrieben, wo auch eine `Exception` geschmissen wird.
Dies soll es einfach im Log machen den `Stacktrace` nach zu verfolgen.

Als Technologie benutzen wir `SLF4J` (Simple Logging Face for Java).
Dies ist nativ in `Spring-Boot 2.x` und lässt sich mit einer einfachen Annotation (`SLF4J`) jeder Klasse hinzufügen.

Wir haben `SLF4J` nicht konfiguriert, also wird standardmäßig `Logback` benutzt.

Wir haben uns dafür entschieden, weil unsere Internetrecherche die meisten Treffer dazu ergeben hat und unser Tutor uns
unabhängig davon zu geraten hat. Die Einfachheit des Tools ist ebenfalls ein Entscheidungsgrund gewesen.
****