[[section-architecture-constraints]]
== Randbedingungen

****
Um unerwartete Verzögerung im Entwicklungsablauf zu vermeiden, haben wir in der Planungsphase und während der
Implementierung der Kernkomponenten berücksichtigt, welche Randbedingungen und technische sowie fachliche
Einschränkungen den Ablauf der Entwicklung beeinflussen könnten.
[cols="1,2" options="header"]
|===
|Bedingung |Erläuterung
| Zusammenarbeit mit anderen Gruppen | _Schnittstellen mit anderen Gruppen beeinflussen unsere Implementierung. Vor
allem, wenn diese Gruppen selbst noch keine abgeschlossenen Konzepte entworfen haben._
| Fehlende Ordnerstruktur in MinIO | _Da MinIO nur eine virtuelle Ordnerstruktur unterstützt, ist die Anlegung einer
eigenen Ordnerstruktur in einer externen Datenbank notwendig._
| Keycloak erschwert UnitTests| _Aufgrund der Sicherheitskomponenten werden die Controller-Tests stark verkompliziert,
da die Sicherheitsfeatures gemockt werden müssen._
|===

All diese möglichen Probleme haben wir jedoch schlussendlich überwunden und konnten das Produkt ohne größere
Schwierigkeiten fertig stellen.
****
