# This is a workflow to generate the documentation automatically.

name: Generate Documentation

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/AutomaticDocDeployment # this will be removed once it's working
jobs:
  # This workflow contains a single job called "build"
  gen_doc:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        java: [11]
    runs-on: ${{ matrix.os }}
    name: asciidoctor to html
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: ${{ matrix.java }}

      - name: Run Gradle test
        run: ./gradlew test

      - name: Run Gradle Java Doc
        run: ./gradlew javadoc

      - name: Get build container
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D doc -a data-uri --backend=html5 -o index.html doc/documentation.adoc"
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doc