# This is a workflow to generate the documentation automatically.

name: Generate Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  gen_doc:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    name: Deploy Documentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      # necessary for the automatic generation of the rest api documentation snippets
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc

      - name: Run Asciidoctor
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D doc -a data-uri --backend=html5 -o index.html doc/documentation.adoc"

      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
